#include "spectre-api-c/c/spectre-algorithm.h"
#include "spectre-api-c/c/spectre-algorithm_v0.h"
#include "spectre-api-c/c/spectre-algorithm_v1.h"
#include "spectre-api-c/c/spectre-algorithm_v2.h"
#include "spectre-api-c/c/spectre-algorithm_v3.h"
// #include "spectre-api-c/c/spectre-marshal-util.h"
// #include "spectre-api-c/c/spectre-marshal.h"
// #include "spectre-api-c/c/spectre-types.h"
// #include "spectre-api-c/c/spectre-util.h"
// #include "spectre-api-c/c/aes.h"
